/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_cleoag_PS3Eye */

#ifndef _Included_ru_cleoag_PS3Eye
#define _Included_ru_cleoag_PS3Eye
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_cleoag_PS3Eye
 * Method:    native_start
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_ru_cleoag_PS3Eye_native_1start
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     ru_cleoag_PS3Eye
 * Method:    native_stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cleoag_PS3Eye_native_1stop
  (JNIEnv *, jobject);

/*
 * Class:     ru_cleoag_PS3Eye
 * Method:    native_update
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cleoag_PS3Eye_native_1update
  (JNIEnv *, jobject);

/*
 * Class:     ru_cleoag_PS3Eye
 * Method:    native_imageCopy
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_ru_cleoag_PS3Eye_native_1imageCopy
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
